### ISSUE TITLE
Where is the html element now ?

### ISSUE THREAD

**Issue by jparish3** [TimvdLippe/iron-lazy-pages#71] opened 2018-08-16 16:45 UTC

**Comment by TimvdLippe** [comment] 2018-08-16 18:09
I am not sure what you mean. The custom element is still there and works as you expect. You can load it using ES modules and the package is distributed on NPM. Please let me know what you are missing.

**Comment by derhuebiii** [comment] 2018-08-20 14:24
I think what he means is the Polymer 2 element (in .html, not in .js)

**Comment by TimvdLippe** [comment] 2018-08-20 14:44
That is correct. This is in line with the guidelines of the Polymer team: https://www.polymer-project.org/blog/2017-08-22-npm-modules.html I am therefore closing this as working as intended.

**Closed as completed by TimvdLippe** 2018-08-20 14:44 UTC
