### ISSUE TITLE
CSS Mixins don't get applied when selected is two-way bound to another element

### ISSUE THREAD

**Issue by cecilia-sanare** [TimvdLippe/iron-lazy-pages#21] opened 2016-06-24 15:02 UTC
### Description

When you two-way bind the `selected` attribute to another element it causes CSS mixins to not apply.
One primary use-case where this seems to be an issue is with `app-location` and `app-route`.
### Expected outcome

paper-card has a box-shadow underneath
### Actual outcome

paper-card doesn't have a box-shadow
### Live Demo

[Live Demo](https://jsbin.com/jotepigumu/2/edit?html,output)

If you remove the `paper-input` then the shadow appears.

**Comment by TimvdLippe** [comment] 2016-06-24 20:55
You forgot to input the paper-card. When I add the import it is working for me.

**Comment by cecilia-sanare** [comment] 2016-06-24 21:10
`paper-card` gets imported when that page is activated.

Also if you remove the `paper-input` then the card has the shadow as desired.

**Comment by cecilia-sanare** [comment] 2016-06-24 22:03
This issue was incorrectly closed.

If you look at the code in `iron-lazy-pages` you'll see that it imports HTML files via the path property on the template when an item/page is selected.

Importing `paper-card` is not a solution because it defeats 50% of the purpose of this component.

**Comment by TimvdLippe** [comment] 2016-06-24 22:04
Reopening for now to reinvestigate.

**Comment by cecilia-sanare** [comment] 2016-06-24 22:44
It seems this is an issue with the importHref function inside of Polymer.

Polymer/polymer#3727

**Update**
This issue has been resolved in the master branch of Polymer, however the fix has yet to be tagged.

**Comment by TimvdLippe** [comment] 2016-06-25 10:45
Okay glad you were able to find the root cause and the Polymer team fixed the issue. I too hastily closed this issue as I did not expect this element to break any CSS, since it does not use any. Thank you for patience, hopefully Polymer 1.6 is published soon!

**Closed as completed by TimvdLippe** 2016-06-25 10:45 UTC
